# Generated by Django 2.2.3 on 2019-12-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20191223_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
